### ISSUE TITLE
What is the process of communication?

### ISSUE THREAD

**Issue by 55** [EbenezerGH/WearableSocketProgramming#1]
Hello, I want to build a application, it will control Arduino with Samsung smartwatch. 
You have done smth similar here. 
Could you please tell me about the process of it communication?
Does Arduino talk to smartphone and then smartphone talks to smartwatch -or- it does it directly?

**Comment by EbenezerGH** [comment]
The communication aspect deals with socket programming.  The arduino will act as a server and the mobile/wearable device will act as a client.

I used a wireless module (https://www.sparkfun.com/products/10050). There are multiple ways to do this, but my method allowed me to create my own accesspoint and control it from there.

**Comment by 55** [comment]
Thanks!
